openapi: 3.0.0
info:
  version: 2017-11-27
  x-release: v4
  title: AmazonMQ Broker Engine Types Tags API
  description: Amazon MQ is a managed message broker service for Apache ActiveMQ and RabbitMQ that makes it easy to set up and operate message brokers in the cloud. A message broker allows software applications and components to communicate using various programming languages, operating systems, and formal messaging protocols.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: mq
  x-aws-signingName: mq
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/mq-2017-11-27.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://mq.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AmazonMQ multi-region endpoint
- url: https://mq.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AmazonMQ multi-region endpoint
- url: http://mq.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AmazonMQ endpoint for China (Beijing) and China (Ningxia)
- url: https://mq.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AmazonMQ endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Tags
paths:
  /v1/tags/{resource-arn}:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: CreateTags
      description: Add a tag to a resource.
      responses:
        '204':
          description: Success
        '480':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                CreateTags480Example:
                  summary: Default CreateTags 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: BadRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
              examples:
                CreateTags481Example:
                  summary: Default CreateTags 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                CreateTags482Example:
                  summary: Default CreateTags 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                CreateTags483Example:
                  summary: Default CreateTags 483 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: resource-arn
        in: path
        required: true
        description: The Amazon Resource Name (ARN) of the resource tag.
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tags:
                  description: The key-value pair for the resource tag.
                  type: object
                  additionalProperties:
                    $ref: '#/components/schemas/__string'
      summary: Amazon MQ Create Tags
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Tags
    get:
      operationId: ListTags
      description: Lists tags for a resource.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListTagsResponse'
              examples:
                ListTags200Example:
                  summary: Default ListTags 200 response
                  x-microcks-default: true
                  value:
                    Tags: example-value
        '480':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                ListTags480Example:
                  summary: Default ListTags 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: BadRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
              examples:
                ListTags481Example:
                  summary: Default ListTags 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                ListTags482Example:
                  summary: Default ListTags 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                ListTags483Example:
                  summary: Default ListTags 483 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: resource-arn
        in: path
        required: true
        description: The Amazon Resource Name (ARN) of the resource tag.
        schema:
          type: string
      summary: Amazon MQ List Tags
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Tags
  /v1/tags/{resource-arn}#tagKeys:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    delete:
      operationId: DeleteTags
      description: Removes a tag from a resource.
      responses:
        '204':
          description: Success
        '480':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                DeleteTags480Example:
                  summary: Default DeleteTags 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: BadRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
              examples:
                DeleteTags481Example:
                  summary: Default DeleteTags 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                DeleteTags482Example:
                  summary: Default DeleteTags 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                DeleteTags483Example:
                  summary: Default DeleteTags 483 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: resource-arn
        in: path
        required: true
        description: The Amazon Resource Name (ARN) of the resource tag.
        schema:
          type: string
      - name: tagKeys
        in: query
        required: true
        description: An array of tag keys to delete
        schema:
          type: array
          items:
            $ref: '#/components/schemas/__string'
      summary: Amazon MQ Delete Tags
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Tags
components:
  schemas:
    NotFoundException: {}
    __string:
      type: string
    ListTagsResponse:
      type: object
      properties:
        Tags:
          allOf:
          - $ref: '#/components/schemas/__mapOf__string'
          - xml:
              name: tags
            description: The key-value pair for the resource tag.
    ForbiddenException: {}
    InternalServerErrorException: {}
    __mapOf__string:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
    BadRequestException: {}
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/mq/
x-hasEquivalentPaths: true
